import { FaShoppingCart } from "react-icons/fa";
export const FeaturedItems = [
  
  {
    id: 1,
  Company : "Air Force 1'07",
    url: "/images/MensPageImg/Airforce1.webp",
    price: 4525,
    cart: <FaShoppingCart />,
    quantity: 1,
    type: "airforce",
    rating: 3,
    stock: "in",
    delivery: "fast",
  },
  {
    id: 2, 
  Company : "Air Force Shadow",
    
    url: "/images/MensPageImg/Airforce2.webp",
    price: 4999,
    cart: <FaShoppingCart />,
    quantity: 1,
    type: "airforce",
    rating: 4,
    stock: "in",
    delivery: "slow",
  },
  {
    id: 3,
  Company : "Air Force 1 LVB",
    
    url: "/images/MensPageImg/Airforce3.webp",
    price: 4555,
    cart: <FaShoppingCart />,
    quantity: 1,
    type: "airforce",
    rating: 3,
    stock: "out",
    delivery: "fast",
  },
  {
    id: 4,
  Company : "Air Force 1 Premium",
    
    url: "/images/MensPageImg/Airforce4.webp",
    price: 5600,
    cart: <FaShoppingCart />,
    quantity: 1,
    type: "airforce",
    rating: 3,
    stock: "in",
    delivery: "fast",
  },
  {
    id: 5,
  Company : "Air Force 1 React",
    
    url: "/images/MensPageImg/Airforce5.webp",
    price: 5799,
    cart: <FaShoppingCart />,
    quantity: 1,
    type: "airforce",
    rating: 4,
    stock: "in",
    delivery: "slow",
  },
  {
    id: 6,
  Company : "Air Force LV8",
     
    url: "/images/MensPageImg/Airforce6.webp",
    price: 5999,
    cart: <FaShoppingCart />,
    quantity: 1,
    type: "airforce",
    rating: 5,
    stock: "in",
    delivery: "fast",
  },
  {
    id: 7,
    Company: "Air Force Mid Fresh",
     
    url: "/images/MensPageImg/Airforce7.webp",
    price: 4500,
    cart: <FaShoppingCart />,
    quantity: 1,
    type: "airforce",
    rating: 5,
    stock: "out",
    delivery: "fast",
  },
  {
    id: 8,
    Company: "Air Jordan XXVII",
     
    url: "/images/crater/crater7.jpg",
    price: 7000,
    cart: <FaShoppingCart />,
    quantity: 1,
    type: "jordans",
    rating: 5,
    stock: "in",
    delivery: "slow",
  },

  {
    id: 9,
   Company: "Air Jordan 1 Mid",
     
    url: "/images/WomenAssets/jordans1.webp",
    price: 6399,
    cart: <FaShoppingCart />,
    quantity: 1,
    type: "jordans",
    rating: 4,
    stock: "in",
    delivery: "fast",
  },
  {
    id: 10,
   Company: "Air Jordan 1 Elevate High SE",
     
    url: "/images/WomenAssets/jordans2.jpg",
    price: 6499,
    cart: <FaShoppingCart />,
    quantity: 1,

    type: "jordans",
    rating: 3,
    stock: "in",
    delivery: "standard",
  },
  {
    id: 11,
   Company: "Air Jordan 1 Zoom",
     
    url: "/images/WomenAssets/jordans3.webp",
    price: 6799,
    cart: <FaShoppingCart />,
    quantity: 1,
    type: "jordans",
    rating: 4,
    stock: "out",
    delivery: "fast",
  },
  {
    id: 12,
   Company: "Air Jordan Aura",
    
    url: "/images/WomenAssets/jordans4.jpg",
    price: 5499,
    cart: <FaShoppingCart />,
    quantity: 1,
    type: "jordans",
    rating: 3,
    stock: "in",
    delivery: "standard",
  },
  {
    id: 13,
   Company: "Air Jordan Loyal ",
    
    url: "/images/WomenAssets/jordans6.jpg",
    price: 7399,
    cart: <FaShoppingCart />,
    quantity: 1,
    type: "jordans",
    rating: 2,
    stock: "in",
    delivery: "fast",
  },
  {
    id: 14,
   Company: "Air Jordan 2 Elevate",
    
    url: "/images/WomenAssets/jordans7.jpg",
    price: 5899,
    cart: <FaShoppingCart />,
    quantity: 1,
    type: "jordans",
    rating: 4,
    stock: "out",
    delivery: "standard",
  },
  {
    id: 15,
  Company : "Crater 0'1",
    
    url: "/images/crater/crater1.jpg",
    price: 5999,
    cart: <FaShoppingCart />,
    quantity: 1,
   type: "crater",
    rating: 4,
    stock: "in",
    delivery: "fast",
  },
  {
    id: 16,
  Company : "Crater 0'2",
    
    url: "/images/crater/crater2.jpg",
    price: 6099,
    cart: <FaShoppingCart />,
    quantity: 1,
   type : "crater",
    rating: 4,
    stock: "in",
    delivery: "fast",
  },
  {
    id: 17,
  Company : "Crater 0'3",
    
    url: "/images/crater/crater3.webp",
    price:3999 ,
    cart: <FaShoppingCart />,
    quantity: 1,
   type : "crater",
    rating: 4,
    stock: "in",
    delivery: "fast",
  },
  {
    id: 18,
  Company : "Crater 0'4",
    
    url: " /images/crater/crater4.webp",
    price: 5500,
    cart: <FaShoppingCart />,
    quantity: 1,
   type : "crater",
    rating: 4,
    stock: "in",
    delivery: "fast",
  },
  {
    id: 19,
  Company : "Crater 0'5",
    
    url: " /images/crater/crater5.webp",
    price: 4500,
    cart: <FaShoppingCart />,
    quantity: 1,
   type: "crater",
    rating: 4,
    stock: "out",
    delivery: "fast",
  },
  {
    id: 20,
  Company : "Crater 0'6",
    
    url: "/images/crater/crater6.webp",
    price: 4525,
    cart: <FaShoppingCart />,
    quantity: 1,
   type: "crater",
    rating: 4,
    stock: "in",
    delivery: "fast",
  },
  {
    id: 21,
  Company : "Crater 0'7",
    
    url: "/images/crater/crater7.jpg",
    price: 4700,
    cart: <FaShoppingCart />,
    quantity: 1,
   type: "crater",
    rating: 4,
    stock: "in",
    delivery: "fast",
  },

  
];
